### ISSUE TITLE
无法引用库，相关包不能够同步下来。

### ISSUE THREAD

**Issue by haibinpark** [nukc/AmountView#1]
我在app/build.gradle中的dependencies 添加 compile 'com.github.nukc.amountview:library:1.0' 依赖，相关包不能够同步下来。
这里是我的项目下的build.gralde配置:
```
allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by nukc** [comment]
我这边测试是可以的，如果要找同类型的控件，你可以看看 https://github.com/himanshu-soni/QuantityView 。 或者你可以看看我写的代码，写的很简单，你可以自己写一个。有什么问题，欢迎提问。
